#ifndef CONFIG_H
#define CONFIG_H

// #define CONFIG_TEST_ENABLED
#define CONFIG_BENCHMARK_ENABLED
#define CONFIG_PRINT_PERFORMANCE_ENABLED
// #define CONFIG_GAME_ENABLED

// #define CONFIG_GRID_ENABLED
#define CONFIG_SCALABLE_GRID_ENABLED
#define CONFIG_KDTREE_ENABLED
// #define CONFIG_GRID_CHECK

#ifdef CONFIG_SCALABLE_GRID_ENABLED
#define CONFIG_SCALABLE_GRID_SIZE 16
#define CONFIG_SCALABLE_GRID_QUICK_SHORT_RANGE_ENEMY_SEARCH 128
#define CONFIG_SCALABLE_GRID_INITIAL_CAPACITY 4096
#endif

#ifdef CONFIG_KDTREE_ENABLED
#define CONFIG_KDTREE_ENEMY_SEARCH
// #define CONFIG_KDTREE_ENEMY_SEARCH_CHECK
#endif

#endif
