#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_TEST_ENABLED
#define CONFIG_BENCHMARK_ENABLED
#define CONFIG_PRINT_PERFORMANCE_ENABLED
// #define CONFIG_GAME_ENABLED

// #define CONFIG_GRID_ENABLED
#define CONFIG_SCALABLE_GRID_ENABLED
#define CONFIG_KDTREE_ENABLED

#ifdef CONFIG_SCALABLE_GRID_ENABLED
#define CONFIG_SCALABLE_GRID_SIZE 16
#define CONFIG_SCALABLE_GRID_QUICK_SHORT_RANGE_ENEMY_SEARCH 128
#define CONFIG_SCALABLE_GRID_INITIAL_CAPACITY 4096
#endif

#define INITIAL_WINDOW_WIDTH 1280
#define INITIAL_WINDOW_HEIGHT 540
#define INITIAL_CAMERA_X -768
#define INITIAL_CAMERA_Y 0
#define INITIAL_CAMERA_Z 4

#endif
